export const MODULE_COMMON = "common";

export const COLOR_MAIN = "#FF6E10";

export const ITEM_STATUS = {
  0: "Not Scanned",
  1: "Pass",
  // 2: "Additional",
  3: "Broken",
  4: "Others",
  5: "Wrong Location",
};

export enum BUTTON_ICON {
  LOADING = "fa-solid fa-spinner-third",
  REMOVE = "fa-solid fa-circle-xmark",
  BARCODE = "fa-solid fa-barcode",
}

export enum CUSTODIAN {
  AAVE = "AAVE",
  AVM = "AVM",
  BB = "BB",
  BMT = "BMT",
  CCC = "CCC",
  CCWB = "CCWB",
  CLUB = "CLUB",
  CWC = "CWC",
  DH = "DH",
  DS = "DS",
  DSC = "DSC",
  DT = "DT",
  FMAC = "FMAC",
  FMDT = "FMDT",
  FMIC = "FMIC",
  FMIN = "FMIN",
  FMMC = "FMMC",
  FMME = "FMME",
  FMPM = "FMPM",
  FMSP = "FMSP",
  FMSX = "FMSX",
  GE = "GE",
  GT = "GT",
  HGBA = "HGBA",
  HILB = "HILB",
  HR = "HR",
  IFAC = "IFAC",
  INAR = "INAR",
  INB = "INB",
  INC = "INC",
  IT = "IT",
  LA = "LA",
  MKT = "MKT",
  "N/A" = "N/A",
  ODS = "ODS",
  OP = "OP",
  PD = "PD",
  RG = "RG",
  SC = "SC",
  SCPS = "SCPS",
  SHE = "SHE",
  SPIL = "SPIL",
  STPF = "STPF",
  SUST = "SUST",
  TONE = "TONE",
  WINC = "WINC",
}

export const STOCK_TAKE_SHEET_ITEM = [
  "Bukrs",
  "Countid",
  "Anln1",
  "Anln2",
  "Txt50",
  "Invnr",
  "Ord41",
  "Ord42",
  "Stort",
  "Ktext",
  "Status",
  "Remark",
];